export const ADD_DATA_IN_CART = 'ADD_DATA_IN_CART';
export const REMOVE_DATA_FROM_CART = 'REMOVE_DATA_FROM_CART';
export const GET_DISCOUNT = "GET_DISCOUNT";
export const TOTAL_AMOUNT = "TOTAL_AMOUNT";